<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\icons\globe.png" />
    <Content Remove="wwwroot\icons\moon.svg" />
    <Content Remove="wwwroot\icons\password_reset.png" />
    <Content Remove="wwwroot\icons\placeholder.png" />
    <Content Remove="wwwroot\icons\profile.png" />
    <Content Remove="wwwroot\icons\search.svg" />
    <Content Remove="wwwroot\icons\sun.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="wwwroot\icons\globe.png" />
    <Resource Include="wwwroot\icons\moon.svg" />
    <Resource Include="wwwroot\icons\password_reset.png" />
    <Resource Include="wwwroot\icons\placeholder.png" />
    <Resource Include="wwwroot\icons\search.svg" />
    <Resource Include="wwwroot\icons\sun.svg" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\js\theme.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
    <Folder Include="wwwroot\images\products\" />
  </ItemGroup>

</Project>
